export const foodCategoryOptions = [
    { label: "Vegetable", value: "VEGETABLE" },
    { label: "Fruit", value: "FRUIT" },
    { label: "Meat", value: "MEAT" },
    { label: "Fish", value: "FISH" },
    { label: "Dairy", value: "DAIRY" },
    { label: "Grain", value: "GRAIN" },
    { label: "Legume", value: "LEGUME" },
    { label: "Nut", value: "NUT" },
    { label: "Egg", value: "EGG" },
    { label: "Sweet", value: "SWEET" },
    { label: "Drink", value: "DRINK" },
    { label: "Sauce", value: "SAUCE" },
    { label: "Oil", value: "OIL" },
    { label: "Spice", value: "SPICE" },
    { label: "Ready meal", value: "READY_MEAL" },
    { label: "Snack", value: "SNACK" },
    { label: "Supplement", value: "SUPPLEMENT" },
    { label: "Protein supplement", value: "PROTEIN_SUPPLEMENT" },
    { label: "Other", value: "OTHER" },
];
